# Generated by Django 4.0.4 on 2022-04-23 23:52

from django.db import migrations, models
import proyectos.models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='archivo',
            field=models.FileField(default='null', upload_to=proyectos.models.upload_file),
            preserve_default=False,
        ),
    ]
